<?php
$parameters = array(
    'db_host' => getenv('MAUTIC_DB_HOST'),
    'db_port' => getenv('MAUTIC_DB_PORT') ?: 3306,
    'db_name' => getenv('MAUTIC_DB_NAME'),
    'db_user' => getenv('MAUTIC_DB_USER'),
    'db_password' => getenv('MAUTIC_DB_PASSWORD'),
    'db_table_prefix' => getenv('MAUTIC_DB_PREFIX') ?: null,
    'db_backup_tables' => false,
    'db_backup_prefix' => 'bak_',
    'admin_email' => getenv('MAUTIC_ADMIN_EMAIL'),
    'admin_password' => getenv('MAUTIC_ADMIN_PASSWORD'),
    'admin_firstname' => getenv('MAUTIC_ADMIN_FIRSTNAME'),
    'admin_lastname' => getenv('MAUTIC_ADMIN_LASTNAME'),
    'mailer_transport' => getenv('MAUTIC_MAILER_TRANSPORT'),
    'mailer_host' => getenv('MAUTIC_MAILER_HOST'),
    'mailer_port' => getenv('MAUTIC_MAILER_PORT'),
    'mailer_user' => getenv('MAUTIC_MAILER_USER'),
    'mailer_password' => getenv('MAUTIC_MAILER_PASSWORD'),
    'mailer_encryption' => getenv('MAUTIC_MAILER_ENCRYPTION'),
    'mailer_auth_mode' => getenv('MAUTIC_MAILER_AUTH_MODE'),
    'mailer_spool_type' => getenv('MAUTIC_MAILER_SPOOL_TYPE') ?: 'file',
    'mailer_spool_path' => getenv('MAUTIC_MAILER_SPOOL_PATH') ?: '%kernel.root_dir%/spool',
); 