name: Setup New Client

on:
  workflow_dispatch:
    inputs:
      client:
        description: 'Nome do cliente'
        required: true
      environment:
        description: 'Ambiente (prod/staging/demo)'
        required: true
        default: 'demo'

env:
  AWS_REGION: us-east-2

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check Base Infrastructure
        run: |
          # Verificar se infra base existe
          VPC_ID=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=mautic-shared-vpc" --query 'Vpcs[0].VpcId' --output text)
          if [ "$VPC_ID" == "None" ]; then
            echo "Erro: Infraestrutura base não encontrada. Execute o workflow setup-base-infra primeiro."
            exit 1
          fi

  setup_client:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Client
        run: |
          ./scripts/setup-client.sh ${{ github.event.inputs.client }} ${{ github.event.inputs.environment }} 